config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  resources :like_dislikes
  #devise_for :users
  resources :posts do
  	resources :comments
    member do
      get :like
    end
  end

  root 'posts#index'

  # Routes match in priority from top to bottom
  # devise_for :users, :controllers => {registerations: 'registerations'}

  devise_for :users, controllers: {
        registerations: 'users/registerations'
      }

      delete 'destroy' => 'comments_controller#destroy', defaults: { format: 'js' }


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get ':user_name', to: 'profiles#show', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/comment.rb
class Comment < ApplicationRecord
  class CommentsCountError < StandardError; end;
  belongs_to :user
  belongs_to :post

  before_create :check_comments_count

  def check_comments_count
    if self.class.where(user_id: self.user_id, post_id: self.post_id).count > 4
      raise CommentsCountError, "You can't create more than 5 comments"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id
		begin
			@comment.save
		rescue Comment::CommentsCountError
			redirect_to root_path
		end
	end

	def destroy
		@comment = @post.comments.find(params[:id])

		if @comment.destroy
			respond_to do |format|
				format.js
			end
			flash[:success] = "comment deleted :("
		end
		#redirect_to root_path
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_post
		@post = Post.find(params[:post_id])
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment_<%=comment.id%>">
  <div class="user-name">
    <div class="user-name">
      <% if comment.user %>
        <%= comment.user.user_name %>
      <% end %>
    </div>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('');

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").fadeOut();