config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  resources :like_dislikes
  #devise_for :users
  resources :posts do
  	resources :comments
    member do
      get :like
    end
  end

  root 'posts#index'

  # Routes match in priority from top to bottom
  # devise_for :users, :controllers => {registerations: 'registerations'}

  devise_for :users, controllers: {
        registerations: 'users/registerations'
      }

      delete 'destroy' => 'comments_controller#destroy', defaults: { format: 'js' }


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get ':user_name', to: 'profiles#show', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/like_dislike.rb
class LikeDislike < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/like_dislikes_controller.rb
class LikeDislikesController < ApplicationController
  before_action :set_like_dislike, only: [:show, :edit, :update, :destroy]

  # GET /like_dislikes
  # GET /like_dislikes.json
  def index
    @like_dislikes = LikeDislike.all
  end

  # GET /like_dislikes/1
  # GET /like_dislikes/1.json
  def show
  end

  # GET /like_dislikes/new
  def new
    @like_dislike = LikeDislike.new
  end

  # GET /like_dislikes/1/edit
  def edit
  end

  # POST /like_dislikes
  # POST /like_dislikes.json
  def create
    @like_dislike = LikeDislike.new(like_dislike_params)

    respond_to do |format|
      if @like_dislike.save
        format.html { redirect_to @like_dislike, notice: 'Like dislike was successfully created.' }
        format.json { render :show, status: :created, location: @like_dislike }
      else
        format.html { render :new }
        format.json { render json: @like_dislike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /like_dislikes/1
  # PATCH/PUT /like_dislikes/1.json
  def update
    respond_to do |format|
      if @like_dislike.update(like_dislike_params)
        format.html { redirect_to @like_dislike, notice: 'Like dislike was successfully updated.' }
        format.json { render :show, status: :ok, location: @like_dislike }
      else
        format.html { render :edit }
        format.json { render json: @like_dislike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /like_dislikes/1
  # DELETE /like_dislikes/1.json
  def destroy
    @like_dislike.destroy
    respond_to do |format|
      format.html { redirect_to like_dislikes_url, notice: 'Like dislike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like_dislike
      @like_dislike = LikeDislike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_dislike_params
      params.fetch(:like_dislike, {})
    end
end

app/helpers/like_dislikes_helper.rb
module LikeDislikesHelper
end

app/views/like_dislikes/_form.html.erb
<%= simple_form_for(@like_dislike) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/like_dislikes/edit.html.erb
<h1>Editing Like Dislike</h1>

<%= render 'form', like_dislike: @like_dislike %>

<%= link_to 'Show', @like_dislike %> |
<%= link_to 'Back', like_dislikes_path %>

app/views/like_dislikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Like Dislikes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @like_dislikes.each do |like_dislike| %>
      <tr>
        <td><%= link_to 'Show', like_dislike %></td>
        <td><%= link_to 'Edit', edit_like_dislike_path(like_dislike) %></td>
        <td><%= link_to 'Destroy', like_dislike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like Dislike', new_like_dislike_path %>

app/views/like_dislikes/new.html.erb
<h1>New Like Dislike</h1>

<%= render 'form', like_dislike: @like_dislike %>

<%= link_to 'Back', like_dislikes_path %>

app/views/like_dislikes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_like_dislike_path(@like_dislike) %> |
<%= link_to 'Back', like_dislikes_path %>